apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
spec:
  selector:
    matchLabels:
      app: quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      imagePullSecrets:
        - name: aws-ecr
      containers:
      - name: quarkus
        image: 543300470803.dkr.ecr.ap-southeast-1.amazonaws.com/quarkus:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: quarkus-config
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 15"]
